Por exceso de descargas de yfinance se ha bloqueado la IP, por lo que no se puede descargar la informaci√≥n de Yahoo Finance, entonces usamos un cvs que descargamos previamente

In [ ]:
import pandas as pd

In [15]:
d1 = pd.read_csv("d1.csv")
d1

,AAPL.Close,MSFT.Close,NVDA.Close,AMZN.Close,META.Close,GOOGL.Close,AVGO.Close,GOOG.Close,TSLA.Close,WMT.Close,INTC.Close,JPM.Close,F.Close,NKE.Close,GS.Close,NFLX.Close,CVX.Close,ADBE.Close,BAC.Close,C.Close
0,182.009995,334.750000,30.121000,170.404495,338.540009,144.991501,66.332001,145.074493,399.926666,48.216667,53.209999,161.699997,21.770000,164.669998,395.329987,597.369995,119.260002,564.369995,46.180000,63.099998
1,179.699997,329.010010,29.290001,167.522003,336.529999,144.399506,67.092003,144.416504,383.196655,47.333332,53.139999,167.830002,24.309999,166.389999,407.480011,591.150024,121.430000,554.000000,47.990002,63.590000
2,174.919998,316.380005,27.604000,164.356995,324.170013,137.774994,64.300003,137.653503,362.706665,47.973331,53.869999,163.779999,23.660000,162.250000,398.630005,567.520020,122.220001,514.429993,47.180000,62.849998
3,172.000000,313.880005,28.177999,163.253998,332.459991,137.747498,63.702999,137.550995,354.899994,47.840000,54.009998,165.520004,24.459999,161.039993,396.929993,553.289978,123.260002,514.119995,48.130001,64.910004
4,172.169998,314.040009,27.247000,162.554001,331.790009,137.016998,61.915001,137.004501,342.320007,48.296665,53.439999,167.160004,24.440001,156.970001,397.510010,541.059998,125.029999,510.700012,49.180000,65.779999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,247.100006,404.000000,130.279999,212.710007,668.130005,179.250000,207.929993,181.190002,330.529999,93.669998,24.270000,261.339996,9.350000,80.279999,626.140015,988.469971,157.889999,444.420013,44.459999,78.540001
788,247.039993,397.899994,126.629997,212.800003,657.500000,175.419998,202.539993,177.369995,302.799988,97.690002,22.990000,257.399994,9.420000,81.720001,614.909973,977.239990,156.419998,443.410004,43.939999,78.139999
789,240.360001,399.730011,131.279999,214.350006,673.700012,172.729996,212.940002,174.699997,290.799988,96.199997,23.520000,258.790009,9.470000,81.169998,617.770020,990.059998,155.139999,441.500000,43.939999,79.070000
790,237.300003,392.529999,120.150002,208.740005,658.239990,168.500000,197.800003,170.210007,281.950012,96.790001,23.090000,259.049988,9.290000,80.019997,608.000000,963.070007,156.669998,437.190002,44.119999,78.870003
791,241.839996,396.989990,124.919998,212.279999,668.200012,170.279999,199.429993,172.220001,292.980011,98.610001,23.730000,264.649994,9.550000,79.430000,622.289978,980.559998,158.619995,438.559998,46.099998,79.949997